# Generated by Django 4.2.23 on 2025-10-28 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0009_brand_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress_message', models.CharField(blank=True, max_length=200)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('scraped_data', models.JSONField(blank=True, help_text='Raw scraped reviews', null=True)),
                ('insights', models.JSONField(blank=True, help_text='Analyzed insights', null=True)),
                ('micro_check_suggestions', models.JSONField(blank=True, help_text='Generated micro-check recommendations', null=True)),
                ('google_rating', models.FloatField(blank=True, null=True)),
                ('google_address', models.CharField(blank=True, max_length=500)),
                ('total_reviews_found', models.IntegerField(blank=True, null=True)),
                ('reviews_analyzed', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='website', help_text='Where they came from', max_length=50)),
                ('converted_to_trial', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, help_text='Linked when prospect converts to customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_analyses', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Review Analysis',
                'verbose_name_plural': 'Review Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='insights_re_created_33cad2_idx'), models.Index(fields=['status'], name='insights_re_status_434b88_idx'), models.Index(fields=['contact_email'], name='insights_re_contact_b82b9c_idx')],
            },
        ),
    ]
