# Generated by Django 4.2.25 on 2025-10-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanalysis',
            name='newest_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewanalysis',
            name='oldest_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
