# Generated by Django 4.2.23 on 2025-10-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_reviewanalysis_newest_review_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanalysis',
            name='place_id',
            field=models.CharField(blank=True, help_text='Google Places ID for direct navigation', max_length=200),
        ),
    ]
