# Generated by Django 4.2.25 on 2025-11-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_add_store_template_stats'),
        ('insights', '0003_add_place_id_to_review_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInsightsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_surveys_completed', models.IntegerField(default=0, help_text='Number of employee pulse surveys completed (unlock at 5)')),
                ('voices_active', models.JSONField(default=dict, help_text='Active status of each voice: {customer: bool, employee: bool, operational: bool}')),
                ('insights_unlocked_at', models.DateTimeField(auto_now_add=True, help_text='When insights were first unlocked for this store')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time insights state was updated')),
                ('previous_health_score', models.IntegerField(default=0, help_text='Previous health score for delta calculation')),
                ('store', models.OneToOneField(help_text='Store this insights state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='insights_state', to='brands.store')),
            ],
            options={
                'verbose_name': 'Store Insights State',
                'verbose_name_plural': 'Store Insights States',
                'db_table': 'store_insights_state',
            },
        ),
    ]
