# Generated by Django 4.2.23 on 2025-11-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_add_store_template_stats'),
        ('insights', '0004_storeinsightsstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanalysis',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Linked store for customer review analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_analyses', to='brands.store'),
        ),
    ]
