services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: peakops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps/api:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/peakops
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: celery -A peakops worker -l info --concurrency=2 --max-tasks-per-child=10 --max-memory-per-child=500000
    volumes:
      - ./apps/api:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/peakops
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    env_file:
      - .env
    stop_grace_period: 10m  # Wait 10 minutes for running tasks to complete before force stop
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  celery-beat:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: celery -A peakops beat -l info
    volumes:
      - ./apps/api:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/peakops
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_POSTHOG_KEY=phc_dbNigyTBRGRceEaS6WBAC82o1U4OJw5I4tUg6Oago2J
      - VITE_POSTHOG_HOST=https://us.i.posthog.com
      - VITE_POSTHOG_ENABLED=true
      - VITE_DEMO_MODE=true
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    depends_on:
      - api
    env_file:
      - .env

  marketing:
    build:
      context: ./apps/marketing
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./apps/marketing:/app
      - marketing_node_modules:/app/node_modules

volumes:
  postgres_data:
  marketing_node_modules: