# Generated by Django 4.2.23 on 2025-11-02 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0010_add_store_template_stats'),
        ('accounts', '0013_add_passwordless_login_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0010_add_textfield_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeVoicePulse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Team Check-In', max_length=200)),
                ('description', models.TextField(default='Quick anonymous survey to help improve daily operations.', help_text='Description shown to employees')),
                ('shift_window', models.CharField(choices=[('OPEN', 'Opening Shift'), ('MID', 'Mid Shift'), ('CLOSE', 'Closing Shift')], default='MID', help_text='When during the shift to send the survey', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish (Español)'), ('fr', 'French (Français)')], default='en', help_text='Primary language for this pulse survey', max_length=5)),
                ('send_time', models.TimeField(blank=True, help_text='Specific time to send (optional, uses shift_window if not set)', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('LOCKED', 'Locked (Awaiting Unlock)')], default='LOCKED', help_text='Unlock after 5 unique respondents in 30 days', max_length=20)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('min_respondents_for_display', models.IntegerField(default=5, help_text='Minimum n for displaying aggregated data (privacy protection)')),
                ('consent_text', models.TextField(default='Anonymous, aggregated. Used to improve daily operations.', help_text='Consent copy shown to employees')),
                ('auto_fix_flow_enabled', models.BooleanField(default=False, help_text='Auto-create ActionItem when bottleneck mentioned ≥3× in 7 days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Account for multi-store management', on_delete=django.db.models.deletion.CASCADE, related_name='employee_voice_pulses', to='accounts.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_voice_pulses', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(help_text='Store this pulse belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='employee_voice_pulses', to='brands.store')),
            ],
            options={
                'db_table': 'employee_voice_pulses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeVoiceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Secure magic link token (hashed)', max_length=64, unique=True)),
                ('delivery_method', models.CharField(choices=[('SMS', 'SMS'), ('QR', 'QR Code'), ('EMAIL', 'Email')], default='SMS', max_length=10)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Magic link expiration (24 hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='employee_voice.employeevoicepulse')),
            ],
            options={
                'db_table': 'employee_voice_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossVoiceCorrelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_type', models.CharField(choices=[('BOTTLENECK_TO_CHECK_FAIL', 'Bottleneck → Check Failure'), ('MOOD_TO_CHECK_FAIL', 'Mood Decline → Check Failure'), ('CONFIDENCE_TO_CHECK_FAIL', 'Low Confidence → Check Failure')], max_length=50)),
                ('strength', models.CharField(choices=[('WEAK', 'Weak'), ('MODERATE', 'Moderate'), ('STRONG', 'Strong')], default='MODERATE', max_length=20)),
                ('bottleneck_type', models.CharField(blank=True, help_text='Which bottleneck is trending', max_length=20)),
                ('avg_mood_score', models.FloatField(blank=True, null=True)),
                ('avg_confidence_score', models.FloatField(blank=True, null=True)),
                ('check_category', models.CharField(blank=True, help_text='Category of micro-checks that are failing', max_length=20)),
                ('check_fail_rate', models.FloatField(blank=True, help_text='Percentage of checks failing in this category', null=True)),
                ('recommendation_text', models.TextField(help_text='Actionable recommendation based on correlation')),
                ('is_actionable', models.BooleanField(default=True, help_text='Can this correlation trigger automated actions?')),
                ('time_window_start', models.DateTimeField()),
                ('time_window_end', models.DateTimeField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_item', models.ForeignKey(blank=True, help_text='Auto-generated action item from this correlation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_correlations', to='inspections.actionitem')),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='employee_voice.employeevoicepulse')),
            ],
            options={
                'db_table': 'employee_voice_correlations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoFixFlowConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bottleneck_threshold', models.IntegerField(default=3, help_text='Number of times bottleneck must be mentioned to trigger')),
                ('time_window_days', models.IntegerField(default=7, help_text='Time window for counting bottleneck mentions')),
                ('bottleneck_to_category_map', models.JSONField(default=dict, help_text='Maps bottleneck types to micro-check categories for corrective actions')),
                ('is_enabled', models.BooleanField(default=True)),
                ('notify_on_creation', models.BooleanField(default=True, help_text='Send notification when ActionItem is auto-created')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pulse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_fix_config', to='employee_voice.employeevoicepulse')),
            ],
            options={
                'db_table': 'employee_voice_auto_fix_configs',
            },
        ),
        migrations.CreateModel(
            name='EmployeeVoiceResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_hash', models.CharField(db_index=True, help_text='SHA-256 hash of device fingerprint + IP + date (non-reversible)', max_length=64)),
                ('mood', models.IntegerField(choices=[(1, '😞 Very Bad'), (2, '😕 Bad'), (3, '😐 Neutral'), (4, '🙂 Good'), (5, '😊 Very Good')], help_text='1-5 emoji slider for mood')),
                ('confidence', models.CharField(choices=[('LOW', 'Could use more training'), ('MEDIUM', 'Mostly confident'), ('HIGH', 'Very confident')], help_text='How confident are you in your role today?', max_length=20)),
                ('bottleneck', models.CharField(blank=True, choices=[('EQUIPMENT', 'Equipment/Tools'), ('STAFFING', 'Staffing/Scheduling'), ('TRAINING', 'Training/Knowledge'), ('SUPPLIES', 'Supplies/Inventory'), ('COMMUNICATION', 'Communication'), ('PROCESSES', 'Processes/Procedures'), ('NONE', 'No bottlenecks')], help_text='Biggest bottleneck faced today (optional)', max_length=20, null=True)),
                ('comment', models.TextField(blank=True, help_text='Optional comment (80-280 chars, role-gated viewing)', max_length=280)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='For hash generation only', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='For hash generation only')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='employee_voice.employeevoiceinvitation')),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='employee_voice.employeevoicepulse')),
            ],
            options={
                'db_table': 'employee_voice_responses',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['pulse', 'completed_at'], name='employee_vo_pulse_i_e096e1_idx'), models.Index(fields=['anonymous_hash', 'completed_at'], name='employee_vo_anonymo_872dda_idx'), models.Index(fields=['bottleneck', 'completed_at'], name='employee_vo_bottlen_ddae69_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='employeevoicepulse',
            index=models.Index(fields=['store', 'is_active'], name='employee_vo_store_i_6238d9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevoicepulse',
            index=models.Index(fields=['account', 'status'], name='employee_vo_account_2c9b42_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevoicepulse',
            index=models.Index(fields=['status', 'unlocked_at'], name='employee_vo_status_83f753_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevoiceinvitation',
            index=models.Index(fields=['token'], name='employee_vo_token_4887f4_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevoiceinvitation',
            index=models.Index(fields=['pulse', 'status'], name='employee_vo_pulse_i_e64817_idx'),
        ),
        migrations.AddIndex(
            model_name='employeevoiceinvitation',
            index=models.Index(fields=['expires_at', 'status'], name='employee_vo_expires_9f070a_idx'),
        ),
        migrations.AddIndex(
            model_name='crossvoicecorrelation',
            index=models.Index(fields=['pulse', 'correlation_type'], name='employee_vo_pulse_i_b9faeb_idx'),
        ),
        migrations.AddIndex(
            model_name='crossvoicecorrelation',
            index=models.Index(fields=['bottleneck_type', 'created_at'], name='employee_vo_bottlen_9d9eed_idx'),
        ),
        migrations.AddIndex(
            model_name='crossvoicecorrelation',
            index=models.Index(fields=['is_resolved', 'created_at'], name='employee_vo_is_reso_fac838_idx'),
        ),
    ]
