# Generated by Django 4.2.25 on 2025-11-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_voice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeevoiceresponse',
            name='employee_vo_bottlen_ddae69_idx',
        ),
        migrations.RemoveField(
            model_name='employeevoiceresponse',
            name='bottleneck',
        ),
        migrations.AddField(
            model_name='employeevoiceresponse',
            name='bottlenecks',
            field=models.JSONField(blank=True, default=list, help_text="Multi-select: What's slowing the team down? (array of Bottleneck choices)"),
        ),
        migrations.AlterField(
            model_name='employeevoiceresponse',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment: Anything we should fix or celebrate today? (80 chars max)', max_length=80),
        ),
        migrations.AlterField(
            model_name='employeevoiceresponse',
            name='confidence',
            field=models.IntegerField(choices=[(1, "❌ No, we're short or disorganized"), (2, '⚠️ Mostly, a few things missing'), (3, "✅ Yes, I'm all set")], help_text='Do you have what you need to do your job well today?'),
        ),
        migrations.AlterField(
            model_name='employeevoiceresponse',
            name='mood',
            field=models.IntegerField(choices=[(1, '😫 Exhausted'), (2, '😐 Meh'), (3, '🙂 Good'), (4, '😄 Great'), (5, '🔥 On Fire')], help_text='1-5 emoji slider for mood'),
        ),
    ]
