# Generated by Django 4.2.25 on 2025-11-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_add_store_template_stats'),
        ('employee_voice', '0002_remove_employeevoiceresponse_employee_vo_bottlen_ddae69_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevoicepulse',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store this pulse belongs to (null = account-wide pulse)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_voice_pulses', to='brands.store'),
        ),
    ]
