# Generated by Django 4.2.25 on 2025-11-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_voice', '0003_make_pulse_store_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeevoiceinvitation',
            name='scheduled_send_at',
            field=models.DateTimeField(blank=True, help_text='Randomized time to send this invitation (for staggered delivery)', null=True),
        ),
        migrations.AddField(
            model_name='employeevoicepulse',
            name='delivery_frequency',
            field=models.CharField(choices=[('LOW', 'Low (1-2 times/week, ~20-30% daily chance)'), ('MEDIUM', 'Medium (2-3 times/week, ~40% daily chance)'), ('HIGH', 'High (3-4 times/week, ~50-60% daily chance)')], default='MEDIUM', help_text='How often employees receive surveys (randomized per employee)', max_length=10),
        ),
        migrations.AddField(
            model_name='employeevoicepulse',
            name='randomization_window_minutes',
            field=models.IntegerField(default=60, help_text='Window size in minutes for randomizing send times within shift (e.g., 30-60 min)'),
        ),
        migrations.AlterField(
            model_name='employeevoiceinvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employeevoiceinvitation',
            index=models.Index(fields=['scheduled_send_at', 'status'], name='employee_vo_schedul_1c9298_idx'),
        ),
    ]
