# Generated by Django 4.2.25 on 2025-11-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_voice', '0004_add_invitation_randomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevoicepulse',
            name='auto_fix_flow_enabled',
            field=models.BooleanField(default=True, help_text='Auto-create ActionItem when bottleneck mentioned ≥3× in 7 days'),
        ),
    ]
