# Generated by Django 4.2.25 on 2025-11-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_voice', '0005_enable_auto_fix_by_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeevoicepulse',
            name='auto_fix_flow_enabled',
        ),
        migrations.DeleteModel(
            name='AutoFixFlowConfig',
        ),
    ]
