# Generated by Django 4.2.23 on 2025-11-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_voice', '0006_remove_auto_fix_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeevoicepulse',
            name='pause_notes',
            field=models.TextField(blank=True, help_text='Additional context for pause', null=True),
        ),
        migrations.AddField(
            model_name='employeevoicepulse',
            name='pause_reason',
            field=models.CharField(blank=True, choices=[('HOLIDAY', 'Holiday/Seasonal Break'), ('UNDER_REVIEW', 'Under Review'), ('LOW_PARTICIPATION', 'Low Participation'), ('RESTRUCTURING', 'Team Restructuring'), ('MIGRATED', 'Migrated to single pulse'), ('OTHER', 'Other')], help_text='Reason for pausing the pulse survey', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeevoicepulse',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when pulse was paused', null=True),
        ),
    ]
