# Generated by Django 4.2.25 on 2025-11-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_voice', '0007_employeevoicepulse_pause_notes_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeevoicepulse',
            constraint=models.UniqueConstraint(
                fields=['account'],
                condition=models.Q(store__isnull=True),
                name='unique_account_pulse',
                violation_error_message='An account can only have one account-wide pulse survey.'
            ),
        ),
    ]
