# Generated by Django 5.2.7 on 2025-10-19 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('STARTER_COACHING', 'Starter Coaching'), ('PRO_COACHING', 'Pro Coaching'), ('ESSENTIALS', 'Corporate Essentials'), ('PROFESSIONAL', 'Corporate Professional'), ('ENTERPRISE_ELITE', 'Enterprise Elite')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Price per store per month', max_digits=10)),
                ('stripe_price_id', models.CharField(help_text='Stripe Price ID', max_length=100)),
                ('stripe_product_id', models.CharField(help_text='Stripe Product ID', max_length=100)),
                ('unlimited_coaching_videos', models.BooleanField(default=False)),
                ('inspection_mode_enabled', models.BooleanField(default=False)),
                ('multi_manager_analytics', models.BooleanField(default=False)),
                ('corporate_dashboards', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('dedicated_success_manager', models.BooleanField(default=False)),
                ('max_videos_per_month', models.IntegerField(blank=True, help_text='Max videos per month, null = unlimited', null=True)),
                ('max_stores', models.IntegerField(blank=True, help_text='Max stores, null = unlimited', null=True)),
                ('max_users', models.IntegerField(blank=True, help_text='Max users, null = unlimited', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_customers',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('INCOMPLETE', 'Incomplete'), ('TRIALING', 'Trialing'), ('UNPAID', 'Unpaid')], default='INCOMPLETE', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('store_count', models.IntegerField(default=1, help_text='Number of stores in subscription')),
                ('trial_converted', models.BooleanField(default=False, help_text='Was this a trial conversion')),
                ('metadata', models.JSONField(default=dict, help_text='Additional subscription metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.stripecustomer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CHECKOUT_COMPLETED', 'Checkout Session Completed'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('SUBSCRIPTION_DELETED', 'Subscription Deleted'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('PAYMENT_FAILED', 'Payment Failed'), ('INVOICE_PAID', 'Invoice Paid'), ('INVOICE_PAYMENT_FAILED', 'Invoice Payment Failed')], max_length=50)),
                ('stripe_event_id', models.CharField(max_length=100, unique=True)),
                ('stripe_event_data', models.JSONField(help_text='Full Stripe event data')),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='billing.subscription')),
            ],
            options={
                'db_table': 'payment_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_event_id'], name='payment_eve_stripe__9ae5b1_idx'), models.Index(fields=['event_type', 'created_at'], name='payment_eve_event_t_e821f3_idx')],
            },
        ),
    ]
