# Generated by Django 4.2.25 on 2025-10-22 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_populate_accounts_from_brands'),
        ('brands', '0008_store_account_alter_store_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SevenShiftsEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seven_shifts_id', models.CharField(db_index=True, help_text='7shifts user ID', max_length=100, unique=True)),
                ('seven_shifts_location_id', models.CharField(blank=True, help_text='7shifts location ID', max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Employee is active in 7shifts')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Last sync from 7shifts')),
                ('account', models.ForeignKey(help_text='Franchisee account', on_delete=django.db.models.deletion.CASCADE, related_name='seven_shifts_employees', to='accounts.account')),
                ('store', models.ForeignKey(blank=True, help_text='Store this employee works at (mapped from location_id)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven_shifts_employees', to='brands.store')),
            ],
            options={
                'verbose_name': '7shifts Employee',
                'verbose_name_plural': '7shifts Employees',
                'db_table': 'seven_shifts_employees',
            },
        ),
        migrations.CreateModel(
            name='SevenShiftsConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token_encrypted', models.BinaryField(help_text='Encrypted 7shifts API access token')),
                ('company_id', models.CharField(help_text='7shifts company ID', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether integration is enabled')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('sync_employees_enabled', models.BooleanField(default=True, help_text='Auto-sync employees from 7shifts')),
                ('sync_shifts_enabled', models.BooleanField(default=True, help_text='Auto-sync shift schedules from 7shifts')),
                ('enforce_shift_schedule', models.BooleanField(default=True, help_text='Only send checks when employee is on shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(help_text='Franchisee account that owns this integration', on_delete=django.db.models.deletion.CASCADE, related_name='seven_shifts_config', to='accounts.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seven_shifts_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '7shifts Configuration',
                'verbose_name_plural': '7shifts Configurations',
                'db_table': 'seven_shifts_configs',
            },
        ),
        migrations.CreateModel(
            name='SevenShiftsSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('EMPLOYEES', 'Employees'), ('SHIFTS', 'Shifts'), ('FULL', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], max_length=20)),
                ('items_synced', models.IntegerField(default=0, help_text='Number of items successfully synced')),
                ('errors_count', models.IntegerField(default=0, help_text='Number of errors encountered')),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Details of any errors that occurred')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven_shifts_sync_logs', to='accounts.account')),
            ],
            options={
                'verbose_name': '7shifts Sync Log',
                'verbose_name_plural': '7shifts Sync Logs',
                'db_table': 'seven_shifts_sync_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['account', 'sync_type', '-started_at'], name='seven_shift_account_c44bc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SevenShiftsShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seven_shifts_shift_id', models.CharField(db_index=True, help_text='7shifts shift ID', max_length=100, unique=True)),
                ('start_time', models.DateTimeField(db_index=True, help_text='Shift start time (UTC)')),
                ('end_time', models.DateTimeField(db_index=True, help_text='Shift end time (UTC)')),
                ('role', models.CharField(blank=True, help_text='Employee role for this shift', max_length=100)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Last sync from 7shifts')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven_shifts_shifts', to='accounts.account')),
                ('employee', models.ForeignKey(help_text='Employee assigned to this shift', on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='integrations.sevenshiftsemployee')),
                ('store', models.ForeignKey(help_text='Store where shift takes place', on_delete=django.db.models.deletion.CASCADE, related_name='seven_shifts_shifts', to='brands.store')),
            ],
            options={
                'verbose_name': '7shifts Shift',
                'verbose_name_plural': '7shifts Shifts',
                'db_table': 'seven_shifts_shifts',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['store', 'start_time', 'end_time'], name='seven_shift_store_i_4e5d08_idx'), models.Index(fields=['employee', 'start_time'], name='seven_shift_employe_50192b_idx'), models.Index(fields=['account', 'start_time'], name='seven_shift_account_13bf36_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sevenshiftsemployee',
            index=models.Index(fields=['account', 'is_active'], name='seven_shift_account_dfcea3_idx'),
        ),
        migrations.AddIndex(
            model_name='sevenshiftsemployee',
            index=models.Index(fields=['store', 'is_active'], name='seven_shift_store_i_7ee0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='sevenshiftsemployee',
            index=models.Index(fields=['email'], name='seven_shift_email_da5ba1_idx'),
        ),
    ]
