# Generated by Django 4.2.25 on 2025-10-27 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_populate_accounts_from_brands'),
        ('brands', '0008_store_account_alter_store_brand'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SevenShiftsLocationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seven_shifts_location_id', models.CharField(db_index=True, help_text='7shifts location ID', max_length=100)),
                ('seven_shifts_location_name', models.CharField(help_text='7shifts location name (for display)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven_shifts_location_mappings', to='accounts.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seven_shifts_location_mappings', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(help_text='PeakOps store this location maps to', on_delete=django.db.models.deletion.CASCADE, related_name='seven_shifts_location_mappings', to='brands.store')),
            ],
            options={
                'verbose_name': '7shifts Location Mapping',
                'verbose_name_plural': '7shifts Location Mappings',
                'db_table': 'seven_shifts_location_mappings',
                'indexes': [models.Index(fields=['account', 'seven_shifts_location_id'], name='seven_shift_account_4bde64_idx')],
                'unique_together': {('account', 'seven_shifts_location_id')},
            },
        ),
    ]
