# Generated by Django 4.2.25 on 2025-10-27 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_sevenshiftslocationmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevenshiftsemployee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked PeakOps user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seven_shifts_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
