# Generated by Django 4.2.25 on 2025-10-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_sevenshiftsemployee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevenshiftsconfig',
            name='sync_role_names',
            field=models.JSONField(blank=True, default=list, help_text="List of 7shifts role names to sync (e.g., ['Server', 'Manager']). Empty means sync all roles."),
        ),
    ]
