# Generated by Django 4.2.23 on 2025-10-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_add_role_filtering'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevenshiftsconfig',
            name='create_users_without_email',
            field=models.BooleanField(default=True, help_text='Create user accounts for employees without email addresses using temporary emails'),
        ),
    ]
