# Generated by Django 4.2.23 on 2025-10-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_add_create_users_without_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevenshiftsemployee',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of role names from 7shifts'),
        ),
    ]
