# Generated by Django 4.2.23 on 2025-10-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_add_google_reviews_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereview',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='True if from authenticated OAuth, False if from public scrape'),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='source',
            field=models.CharField(choices=[('oauth', 'OAuth Sync'), ('scraped', 'Public Scrape')], db_index=True, default='oauth', help_text='Where this review came from', max_length=20),
        ),
        migrations.AddIndex(
            model_name='googlereview',
            index=models.Index(fields=['source', 'is_verified'], name='google_revi_source_28f017_idx'),
        ),
        migrations.AddIndex(
            model_name='googlereview',
            index=models.Index(fields=['account', 'source', '-review_created_at'], name='google_revi_account_907179_idx'),
        ),
    ]
