# Generated by Django 4.2.25 on 2025-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_add_review_source_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlereviewsconfig',
            name='google_account_id',
            field=models.CharField(blank=True, default='', help_text='Google Business Profile account ID', max_length=200),
        ),
    ]
