# Generated by Django 4.2.25 on 2025-10-30 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_brand_subtype'),
        ('integrations', '0009_alter_googlereviewsconfig_google_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlelocation',
            name='store',
            field=models.OneToOneField(blank=True, help_text='PeakOps store this location maps to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_location', to='brands.store'),
        ),
    ]
