# Generated by Django 4.2.25 on 2025-11-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_alter_googlelocation_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlelocation',
            name='place_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google Places API place_id', max_length=200),
        ),
        migrations.AddField(
            model_name='googlelocation',
            name='place_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for this location', max_length=500),
        ),
    ]
