# Generated by Django 4.2.25 on 2025-11-04 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0011_googlelocation_place_id_googlelocation_place_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField(help_text='The reply text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='DRAFT', help_text='Draft, Published, or Failed', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the response was published to Google', null=True)),
                ('was_ai_suggested', models.BooleanField(default=False, help_text='Was this generated by AI?')),
                ('ai_suggestion_tone', models.CharField(blank=True, choices=[('PROFESSIONAL', 'Professional'), ('FRIENDLY', 'Friendly'), ('APOLOGETIC', 'Apologetic')], help_text='Tone used for AI suggestion', max_length=20, null=True)),
                ('google_reply_id', models.CharField(blank=True, help_text='Google reply ID from API (for OAuth reviews)', max_length=200, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if publish failed', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this response', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(help_text='The review this response is for', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='integrations.googlereview')),
            ],
            options={
                'verbose_name': 'Review Response',
                'verbose_name_plural': 'Review Responses',
                'db_table': 'review_responses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review', 'status'], name='review_resp_review__c00e4a_idx'), models.Index(fields=['created_by', '-created_at'], name='review_resp_created_7e861a_idx'), models.Index(fields=['status', '-created_at'], name='review_resp_status_9e8c64_idx')],
            },
        ),
    ]
