# Generated by Django 4.2.25 on 2025-11-05 01:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_passwordless_login_tokens'),
        ('integrations', '0012_add_review_response_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(help_text='Topic/theme being tracked', max_length=200)),
                ('category', models.CharField(blank=True, help_text='Category (food, service, cleanliness, etc.)', max_length=100, null=True)),
                ('overall_sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], default='NEUTRAL', help_text='Overall sentiment for this topic', max_length=20)),
                ('trend_direction', models.CharField(choices=[('INCREASING', '↑ Increasing'), ('STABLE', '→ Stable'), ('DECREASING', '↓ Decreasing'), ('NEW', '🆕 New')], default='STABLE', help_text='Trend direction over time', max_length=20)),
                ('trend_velocity', models.FloatField(default=0.0, help_text='Rate of change (mentions per week)')),
                ('current_mentions', models.IntegerField(default=0, help_text='Mentions in current period')),
                ('previous_mentions', models.IntegerField(default=0, help_text='Mentions in previous period')),
                ('percent_change', models.FloatField(blank=True, help_text='Percentage change from previous period', null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='When this topic was first detected')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When trend was last calculated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this topic is still being mentioned')),
                ('account', models.ForeignKey(help_text='Account this trend belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topic_trends', to='accounts.account')),
                ('location', models.ForeignKey(blank=True, help_text='Specific location (null = account-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_trends', to='integrations.googlelocation')),
            ],
            options={
                'verbose_name': 'Topic Trend',
                'verbose_name_plural': 'Topic Trends',
                'db_table': 'topic_trends',
                'ordering': ['-current_mentions', 'topic'],
                'indexes': [models.Index(fields=['account', '-current_mentions'], name='topic_trend_account_c82a32_idx'), models.Index(fields=['location', '-current_mentions'], name='topic_trend_locatio_c5953d_idx'), models.Index(fields=['trend_direction', '-current_mentions'], name='topic_trend_trend_d_8f6e4b_idx'), models.Index(fields=['overall_sentiment', '-current_mentions'], name='topic_trend_overall_bbd76d_idx'), models.Index(fields=['is_active', '-last_updated'], name='topic_trend_is_acti_3eab3e_idx')],
                'unique_together': {('account', 'location', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='ReviewTopicSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(help_text='Topic/theme being tracked', max_length=200)),
                ('mention_count', models.IntegerField(default=0, help_text='Number of times mentioned in period')),
                ('positive_mentions', models.IntegerField(default=0, help_text='Mentions in positive reviews (4-5 stars)')),
                ('negative_mentions', models.IntegerField(default=0, help_text='Mentions in negative reviews (1-3 stars)')),
                ('avg_sentiment', models.FloatField(blank=True, help_text='Average sentiment score for this topic (-1 to 1)', null=True)),
                ('snapshot_date', models.DateField(help_text='Date this snapshot represents')),
                ('window_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='Aggregation window type', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Account this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topic_snapshots', to='accounts.account')),
                ('location', models.ForeignKey(blank=True, help_text='Specific location (null = account-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_snapshots', to='integrations.googlelocation')),
            ],
            options={
                'verbose_name': 'Review Topic Snapshot',
                'verbose_name_plural': 'Review Topic Snapshots',
                'db_table': 'review_topic_snapshots',
                'ordering': ['-snapshot_date', 'topic'],
                'indexes': [models.Index(fields=['account', 'topic', '-snapshot_date'], name='review_topi_account_15a874_idx'), models.Index(fields=['location', 'topic', '-snapshot_date'], name='review_topi_locatio_634234_idx'), models.Index(fields=['snapshot_date', 'window_type'], name='review_topi_snapsho_8229a6_idx')],
                'unique_together': {('account', 'location', 'topic', 'snapshot_date', 'window_type')},
            },
        ),
    ]
