# Generated by Django 4.2.25 on 2025-11-11 22:15

from django.db import migrations
import json


def setup_seven_shifts_periodic_tasks(apps, schema_editor):
    """Set up Celery Beat periodic tasks for 7shifts integration"""

    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')

    # Create schedules
    daily_2am, _ = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='2',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    daily_3am, _ = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='3',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    every_12_hours, _ = IntervalSchedule.objects.get_or_create(
        every=12,
        period='hours'
    )

    # Create periodic tasks

    # 1. Full sync (employees + shifts) - Daily at 2 AM UTC
    PeriodicTask.objects.get_or_create(
        name='7shifts: Daily Full Sync',
        defaults={
            'task': 'integrations.sync_all_seven_shifts_accounts',
            'crontab': daily_2am,
            'enabled': True,
            'description': 'Full sync of employees and shifts for all 7shifts accounts'
        }
    )

    # 2. Employee sync - Daily at 3 AM UTC
    PeriodicTask.objects.get_or_create(
        name='7shifts: Daily Employee Sync',
        defaults={
            'task': 'integrations.sync_seven_shifts_employees',
            'crontab': daily_3am,
            'enabled': True,
            'description': 'Sync employee roster for all 7shifts accounts'
        }
    )

    # 3. Shift sync - Every 12 hours
    PeriodicTask.objects.get_or_create(
        name='7shifts: Twice Daily Shift Sync',
        defaults={
            'task': 'integrations.sync_seven_shifts_shifts',
            'interval': every_12_hours,
            'enabled': True,
            'kwargs': json.dumps({'days_ahead': 14}),
            'description': 'Sync shift schedules (14 days ahead) for all 7shifts accounts'
        }
    )


def remove_seven_shifts_periodic_tasks(apps, schema_editor):
    """Remove 7shifts periodic tasks (reverse migration)"""

    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    # Delete the tasks
    PeriodicTask.objects.filter(
        name__in=[
            '7shifts: Daily Full Sync',
            '7shifts: Daily Employee Sync',
            '7shifts: Twice Daily Shift Sync',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_topictrend_reviewtopicsnapshot'),
        ('django_celery_beat', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            setup_seven_shifts_periodic_tasks,
            remove_seven_shifts_periodic_tasks
        ),
    ]
