# Generated by Django 4.2.25 on 2025-11-05 02:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_add_store_template_stats'),
        ('accounts', '0013_add_passwordless_login_tokens'),
        ('integrations', '0013_topictrend_reviewtopicsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yelp_business_id', models.CharField(db_index=True, help_text='Yelp business ID', max_length=200, unique=True)),
                ('business_name', models.CharField(help_text='Business name on Yelp', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Business address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('yelp_url', models.URLField(blank=True, help_text='URL to Yelp page')),
                ('average_rating', models.FloatField(blank=True, help_text='Average Yelp rating', null=True)),
                ('total_review_count', models.IntegerField(default=0, help_text='Total reviews on Yelp')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is actively synced')),
                ('synced_at', models.DateTimeField(blank=True, help_text='Last sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Account this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='yelp_locations', to='accounts.account')),
                ('store', models.OneToOneField(blank=True, help_text='Associated PeakOps store (if linked)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yelp_location', to='brands.store')),
            ],
            options={
                'verbose_name': 'Yelp Location',
                'verbose_name_plural': 'Yelp Locations',
                'db_table': 'yelp_locations',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='YelpReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yelp_review_id', models.CharField(db_index=True, help_text='Yelp review ID', max_length=200, unique=True)),
                ('reviewer_name', models.CharField(blank=True, help_text='Reviewer display name', max_length=200)),
                ('reviewer_location', models.CharField(blank=True, help_text='Reviewer location (e.g., "San Francisco, CA")', max_length=200)),
                ('rating', models.IntegerField(help_text='Star rating 1-5')),
                ('review_text', models.TextField(blank=True, help_text='Review comment text')),
                ('is_elite', models.BooleanField(default=False, help_text='Whether reviewer is Yelp Elite')),
                ('check_in_count', models.IntegerField(default=0, help_text='Number of check-ins at this business')),
                ('review_created_at', models.DateTimeField(db_index=True, help_text='When review was posted on Yelp')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Last sync from Yelp')),
                ('needs_analysis', models.BooleanField(db_index=True, default=True, help_text='Review needs AI analysis')),
                ('analyzed_at', models.DateTimeField(blank=True, help_text='When AI analysis was completed', null=True)),
                ('source', models.CharField(choices=[('scraped', 'Public Scrape')], db_index=True, default='scraped', help_text='Where this review came from (Yelp only supports scraping)', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Always False for Yelp (no official API for reviews)')),
                ('account', models.ForeignKey(help_text='Account this review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='yelp_reviews', to='accounts.account')),
                ('location', models.ForeignKey(help_text='Yelp location this review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='integrations.yelplocation')),
            ],
            options={
                'verbose_name': 'Yelp Review',
                'verbose_name_plural': 'Yelp Reviews',
                'db_table': 'yelp_reviews',
                'ordering': ['-review_created_at'],
            },
        ),
        migrations.CreateModel(
            name='YelpReviewAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topics', models.JSONField(default=list, help_text="List of topics mentioned (e.g., ['cleanliness', 'service'])")),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment score from -1 (negative) to 1 (positive)', null=True)),
                ('actionable_issues', models.JSONField(default=list, help_text="List of specific, actionable issues (e.g., 'Bathroom sink was dirty')")),
                ('suggested_category', models.CharField(blank=True, help_text='Suggested micro-check category if issues found', max_length=100)),
                ('confidence', models.FloatField(default=0.0, help_text='AI confidence score 0-1')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='gpt-4', help_text='AI model used for analysis', max_length=50)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='integrations.yelpreview')),
            ],
            options={
                'verbose_name': 'Yelp Review Analysis',
                'verbose_name_plural': 'Yelp Review Analyses',
                'db_table': 'yelp_review_analysis',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='yelpreview',
            index=models.Index(fields=['location', 'rating', '-review_created_at'], name='yelp_review_locatio_e2f035_idx'),
        ),
        migrations.AddIndex(
            model_name='yelpreview',
            index=models.Index(fields=['account', '-review_created_at'], name='yelp_review_account_7d0432_idx'),
        ),
        migrations.AddIndex(
            model_name='yelpreview',
            index=models.Index(fields=['needs_analysis', 'rating'], name='yelp_review_needs_a_c18fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='yelpreview',
            index=models.Index(fields=['source', 'is_verified'], name='yelp_review_source_e00ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='yelplocation',
            index=models.Index(fields=['account', 'is_active'], name='yelp_locati_account_1d8de8_idx'),
        ),
        migrations.AddIndex(
            model_name='yelplocation',
            index=models.Index(fields=['yelp_business_id'], name='yelp_locati_yelp_bu_66617f_idx'),
        ),
    ]
