# Generated by Django 4.2.23 on 2025-11-05 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_passwordless_login_tokens'),
        ('integrations', '0014_add_yelp_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_encrypted', models.BinaryField(help_text='Encrypted Yelp Fusion API key')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this integration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time reviews were synced', null=True)),
                ('account', models.OneToOneField(help_text='Account this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='yelp_config', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Yelp Configuration',
                'verbose_name_plural': 'Yelp Configurations',
                'db_table': 'yelp_config',
            },
        ),
    ]
