# Generated by Django 4.2.25 on 2025-11-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_setup_seven_shifts_celery_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereviewanalysis',
            name='categories',
            field=models.JSONField(default=list, help_text="High-level categories for this review (e.g., ['Food Quality', 'Service'])"),
        ),
    ]
