# Generated by Django 4.2.23 on 2025-11-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_yelpconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YelpConfig',
        ),
    ]
