# Generated by Django 4.2.23 on 2025-11-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_remove_yelp_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereviewanalysis',
            name='categories',
            field=models.JSONField(default=list, help_text="List of categories this review belongs to (e.g., ['Food Quality', 'Service'])"),
        ),
    ]
