# Generated by Django 4.2.23 on 2025-10-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_migrate_trial_admin_to_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When user completed onboarding flow', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('GM', 'General Manager'), ('INSPECTOR', 'Inspector'), ('TRIAL_ADMIN', 'Trial Admin')], default='INSPECTOR', max_length=20),
        ),
    ]
