# Generated by Django 4.2.25 on 2025-10-22 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_store_micro_check_send_time'),
        ('accounts', '0007_add_onboarding_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Franchisee/operator name (e.g., 'John's Franchise Group')", max_length=200)),
                ('company_name', models.CharField(blank=True, help_text='Legal company name', max_length=200)),
                ('billing_email', models.EmailField(blank=True, help_text='Email for billing and invoices', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Parent brand this account operates under', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='brands.brand')),
                ('owner', models.ForeignKey(help_text='Primary account owner (franchisee)', on_delete=django.db.models.deletion.PROTECT, related_name='owned_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Franchisee account this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.account'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['brand', 'is_active'], name='accounts_brand_i_2fcd58_idx'),
        ),
    ]
