# Generated by Django 4.2.25 on 2025-10-27 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_populate_accounts_from_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('GM', 'General Manager'), ('INSPECTOR', 'Inspector'), ('EMPLOYEE', 'Employee'), ('TRIAL_ADMIN', 'Trial Admin')], default='EMPLOYEE', max_length=20),
        ),
        migrations.CreateModel(
            name='MicroCheckDeliveryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_recipients', models.CharField(choices=[('MANAGERS_ONLY', 'Managers Only'), ('ALL_EMPLOYEES', 'All Employees')], default='MANAGERS_ONLY', help_text='Who should receive micro-checks', max_length=20)),
                ('cadence_mode', models.CharField(choices=[('DAILY', 'Daily'), ('RANDOMIZED', 'Randomized Schedule')], default='DAILY', help_text='How often to send micro-checks', max_length=20)),
                ('min_day_gap', models.PositiveSmallIntegerField(default=1, help_text='Minimum days between micro-checks (1-7)')),
                ('max_day_gap', models.PositiveSmallIntegerField(default=3, help_text='Maximum days between micro-checks (1-7)')),
                ('randomize_recipients', models.BooleanField(default=False, help_text='Randomly select a percentage of eligible recipients')),
                ('recipient_percentage', models.PositiveSmallIntegerField(default=100, help_text='Percentage of eligible recipients to send to (1-100)')),
                ('last_sent_date', models.DateField(blank=True, help_text='Last date a micro-check was sent (for calculating next send)', null=True)),
                ('next_send_date', models.DateField(blank=True, help_text='Next scheduled send date (calculated for randomized mode)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(help_text='Account this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='micro_check_delivery_config', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Micro-Check Delivery Configuration',
                'verbose_name_plural': 'Micro-Check Delivery Configurations',
                'db_table': 'micro_check_delivery_configs',
            },
        ),
    ]
