# Generated by Django 4.2.25 on 2025-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_micro_check_delivery_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='micro_check_last_sent_date',
            field=models.DateField(blank=True, help_text='Last date this employee received a micro-check', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='micro_check_next_send_date',
            field=models.DateField(blank=True, help_text="Next scheduled date for this employee's micro-check", null=True),
        ),
    ]
