# Generated by Django 4.2.23 on 2025-10-28 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_per_employee_micro_check_scheduling'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When impersonation ended', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of super admin', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why impersonation was needed')),
                ('impersonated_account', models.ForeignKey(blank=True, help_text='The account being accessed (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions', to='accounts.account')),
                ('impersonated_user', models.ForeignKey(help_text='The user being impersonated', on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_as_target', to=settings.AUTH_USER_MODEL)),
                ('super_admin', models.ForeignKey(help_text='The super admin performing the impersonation', on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_as_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'impersonation_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['super_admin', 'started_at'], name='impersonati_super_a_4560b3_idx'), models.Index(fields=['impersonated_user', 'started_at'], name='impersonati_imperso_5768d6_idx'), models.Index(fields=['impersonated_account', 'started_at'], name='impersonati_imperso_9527d1_idx')],
            },
        ),
    ]
