# Generated by Django 4.2.25 on 2025-10-28 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_impersonation_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordlessLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passwordless_login_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'expires_at'], name='passwordles_token_97544a_idx')],
            },
        ),
    ]
