# Generated by Django 4.2.25 on 2025-11-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_passwordless_login_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_set_by_user_at',
            field=models.DateTimeField(blank=True, help_text='When user first set their own password (vs admin-assigned)', null=True),
        ),
    ]
