# Generated by Django 4.2.25 on 2025-11-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_passwordless_login_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_set_by_user_at',
            field=models.DateTimeField(blank=True, help_text='When user first set their own password (vs admin-assigned)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('GM', 'Manager'), ('INSPECTOR', 'Inspector'), ('EMPLOYEE', 'Employee'), ('TRIAL_ADMIN', 'Trial Admin')], default='EMPLOYEE', max_length=20),
        ),
    ]
