# Generated by Django 4.2.25 on 2025-11-12 00:07

from django.db import migrations, models


def add_password_set_by_user_at_if_not_exists(apps, schema_editor):
    """Add password_set_by_user_at field if it doesn't exist"""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='users' AND column_name='password_set_by_user_at'
        """)
        if cursor.fetchone() is None:
            # Field doesn't exist, add it
            cursor.execute("""
                ALTER TABLE users
                ADD COLUMN password_set_by_user_at TIMESTAMP WITH TIME ZONE NULL
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_passwordless_login_tokens'),
    ]

    operations = [
        migrations.RunPython(add_password_set_by_user_at_if_not_exists, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('GM', 'Manager'), ('INSPECTOR', 'Inspector'), ('EMPLOYEE', 'Employee'), ('TRIAL_ADMIN', 'Trial Admin')], default='EMPLOYEE', max_length=20),
        ),
    ]
