# Generated by Django 4.2.23 on 2025-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_password_set_by_user_at_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcheckdeliveryconfig',
            name='distribution_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable micro-check distribution system-wide'),
        ),
    ]
