# Generated by Django 4.2.23 on 2025-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_distribution_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehaviorevent',
            name='event_type',
            field=models.CharField(choices=[('DEMO_STARTED', 'Demo Started'), ('DEMO_COMPLETED', 'Demo Completed'), ('DEMO_SKIPPED', 'Demo Skipped'), ('UPLOAD_INITIATED', 'Upload Initiated'), ('UPLOAD_COMPLETED', 'Upload Completed'), ('UPLOAD_FAILED', 'Upload Failed'), ('LOGIN', 'User Login'), ('DASHBOARD_VIEW', 'Dashboard Viewed'), ('VIDEO_VIEW', 'Video Viewed'), ('INSPECTION_VIEW', 'Inspection Viewed'), ('TRIAL_EXTENDED', 'Trial Extended'), ('UPGRADE_CLICKED', 'Upgrade Button Clicked'), ('BILLING_VIEW', 'Billing Page Viewed'), ('INACTIVITY_7_DAYS', '7 Days Inactive'), ('TRIAL_EXPIRY_WARNING', 'Trial Expiry Warning Shown'), ('SESSION_TIMEOUT', 'Session Timed Out'), ('PAGE_VIEW', 'Page Viewed'), ('FEATURE_ACCESSED', 'Feature Accessed'), ('TAB_SWITCHED', 'Tab Switched'), ('STORE_SWITCHED', 'Store Switched'), ('CHECK_CREATED', 'Check Created'), ('CHECK_STARTED', 'Check Started'), ('CHECK_COMPLETED', 'Check Completed'), ('CHECK_SKIPPED', 'Check Skipped'), ('CORRECTIVE_ACTION_CREATED', 'Corrective Action Created'), ('CORRECTIVE_ACTION_RESOLVED', 'Corrective Action Resolved'), ('PULSE_CREATED', 'Pulse Survey Created'), ('PULSE_CONFIGURED', 'Pulse Survey Configured'), ('PULSE_PAUSED', 'Pulse Survey Paused'), ('PULSE_RESUMED', 'Pulse Survey Resumed'), ('INVITATION_SENT', 'Survey Invitation Sent'), ('RESPONSE_VIEWED', 'Survey Response Viewed'), ('PULSE_ANALYTICS_VIEWED', 'Pulse Analytics Viewed'), ('TEMPLATE_VIEWED', 'Template Viewed'), ('TEMPLATE_SELECTED', 'Template Selected'), ('TEMPLATE_CUSTOMIZED', 'Template Customized'), ('AI_GENERATION_USED', 'AI Generation Used'), ('TEMPLATE_CREATED', 'Custom Template Created'), ('INSIGHTS_VIEWED', 'Insights Page Viewed'), ('REPORT_FILTERED', 'Report Filtered'), ('DASHBOARD_ACCESSED', 'Dashboard Accessed'), ('EXPORT_CLICKED', 'Export Clicked'), ('SEARCH_PERFORMED', 'Search Performed'), ('PHOTO_UPLOADED', 'Photo Uploaded'), ('VIDEO_UPLOADED', 'Video Uploaded'), ('MEDIA_VIEWED', 'Media Viewed'), ('SETTINGS_VIEWED', 'Settings Viewed'), ('SETTINGS_UPDATED', 'Settings Updated'), ('USER_INVITED', 'User Invited'), ('INTEGRATION_CONFIGURED', 'Integration Configured')], max_length=50),
        ),
    ]
