# Generated by Django 4.2.23 on 2025-10-06 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brand_has_enterprise_access'),
        ('micro_checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microchecktemplate',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand that owns this template (null = global/system template)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_check_templates', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='microchecktemplate',
            name='include_in_rotation',
            field=models.BooleanField(default=True, help_text='Include in daily auto-rotation'),
        ),
        migrations.AddField(
            model_name='microchecktemplate',
            name='is_local',
            field=models.BooleanField(default=False, help_text='Local template (franchise-specific) vs global (brand-wide)'),
        ),
        migrations.AddField(
            model_name='microchecktemplate',
            name='rotation_priority',
            field=models.IntegerField(default=50, help_text='Priority for selection (0-100, higher = more likely)'),
        ),
        migrations.AddField(
            model_name='microchecktemplate',
            name='visual_reference_image',
            field=models.ImageField(blank=True, help_text="Optional reference image showing 'what good looks like'", null=True, upload_to='micro_checks/references/'),
        ),
    ]
