# Generated by Django 4.2.24 on 2025-10-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_store_timezone'),
        ('micro_checks', '0002_add_template_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='Days with at least one completed run')),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0, help_text='Total runs completed')),
                ('last_completion_date', models.DateField(blank=True, help_text='Date in store TZ of last completed run', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='brands.store')),
            ],
            options={
                'db_table': 'store_streaks',
                'indexes': [models.Index(fields=['store'], name='store_strea_store_i_2ecdaf_idx')],
            },
        ),
    ]
