# Generated by Django 4.2.23 on 2025-10-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_checks', '0003_storestreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='created_from',
            field=models.CharField(choices=[('MICRO_CHECK', 'Micro Check'), ('MANUAL', 'Manual'), ('AI_DETECTED', 'AI Detected')], default='MICRO_CHECK', max_length=20),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='fixed_during_session',
            field=models.BooleanField(default=False, help_text='Fixed immediately during check session'),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='verification_confidence',
            field=models.FloatField(blank=True, help_text='AI confidence score 0-1', null=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When AI verified the fix', null=True),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20),
        ),
    ]
