# Generated by Django 4.2.23 on 2025-10-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_checks', '0004_correctiveaction_created_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microchecktemplate',
            name='applicable_subtypes',
            field=models.JSONField(blank=True, default=list, help_text="Array of brand subtypes this template applies to (e.g., ['QSR', 'FAST_CASUAL']). Empty = applies to all."),
        ),
    ]
