# Generated by Django 4.2.23 on 2025-10-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_checks', '0005_microchecktemplate_applicable_subtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='microchecktemplate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about this template (e.g., review counts, generation params)'),
        ),
        migrations.AddField(
            model_name='microchecktemplate',
            name='source',
            field=models.CharField(default='manual', help_text="Source of this template (e.g., 'manual', 'google_reviews', 'ai_generated')", max_length=50),
        ),
    ]
