# Generated by Django 4.2.25 on 2025-10-31 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_brand_subtype'),
        ('accounts', '0013_add_passwordless_login_tokens'),
        ('micro_checks', '0006_add_source_and_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='microchecktemplate',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account for ACCOUNT/STORE level templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_check_templates', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='microchecktemplate',
            name='level',
            field=models.CharField(choices=[('BRAND', 'Brand Level'), ('ACCOUNT', 'Account Level'), ('STORE', 'Store Level')], db_index=True, default='BRAND', help_text='Template hierarchy level: BRAND (franchisor), ACCOUNT (franchisee), or STORE (location-specific)', max_length=20),
        ),
        migrations.AddField(
            model_name='microchecktemplate',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store for STORE level templates only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_check_templates', to='brands.store'),
        ),
        migrations.AddIndex(
            model_name='microchecktemplate',
            index=models.Index(fields=['level', 'brand'], name='micro_check_level_d5aad9_idx'),
        ),
        migrations.AddIndex(
            model_name='microchecktemplate',
            index=models.Index(fields=['level', 'account'], name='micro_check_level_6aad65_idx'),
        ),
        migrations.AddIndex(
            model_name='microchecktemplate',
            index=models.Index(fields=['level', 'store'], name='micro_check_level_4b78bd_idx'),
        ),
    ]
