# Generated by Django 4.2.25 on 2025-10-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_add_store_template_stats'),
        ('micro_checks', '0007_microchecktemplate_account_microchecktemplate_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTemplateStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fails', models.IntegerField(default=0, help_text='Count of FAIL + NEEDS_ATTENTION responses')),
                ('total', models.IntegerField(default=0, help_text='Count of all responded checks')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.store')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_checks.microchecktemplate')),
            ],
            options={
                'db_table': 'store_template_stats',
                'indexes': [models.Index(fields=['store', 'template'], name='store_templ_store_i_a99376_idx'), models.Index(fields=['last_updated_at'], name='store_templ_last_up_866eed_idx')],
                'unique_together': {('store', 'template')},
            },
        ),
    ]
