# Generated by Django 4.2.25 on 2025-10-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_add_store_template_stats'),
        ('micro_checks', '0008_add_store_template_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroCheckMLMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_score', models.FloatField(help_text='Rule-based priority score')),
                ('ml_score', models.FloatField(blank=True, help_text='ML-predicted usefulness probability (p_personalized)', null=True)),
                ('personalized_score', models.FloatField(blank=True, help_text='Blended score (rule + ML)', null=True)),
                ('final_score', models.FloatField(help_text='Final normalized score after constraints')),
                ('selection_method', models.CharField(choices=[('ML_HYBRID', 'ML Hybrid'), ('RULE_BASED', 'Rule Based'), ('FALLBACK', 'Fallback (No Model)')], default='RULE_BASED', max_length=20)),
                ('model_version', models.CharField(blank=True, help_text='Model identifier/version used', max_length=100)),
                ('training_date', models.DateTimeField(blank=True, help_text='When the model was trained', null=True)),
                ('training_f1_score', models.FloatField(blank=True, help_text='F1 score of the model used', null=True)),
                ('local_prior', models.FloatField(blank=True, help_text='Local failure rate (Beta-smoothed)', null=True)),
                ('local_total', models.IntegerField(blank=True, help_text='Number of responses at store+template', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_item', models.OneToOneField(help_text='Run item this scoring applies to', on_delete=django.db.models.deletion.CASCADE, related_name='ml_metrics', to='micro_checks.microcheckrunitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.store')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_checks.microchecktemplate')),
            ],
            options={
                'db_table': 'micro_check_ml_metrics',
                'indexes': [models.Index(fields=['store', 'created_at'], name='micro_check_store_i_d5bf44_idx'), models.Index(fields=['selection_method', 'created_at'], name='micro_check_selecti_247a4b_idx'), models.Index(fields=['template', 'created_at'], name='micro_check_templat_0f24cd_idx')],
            },
        ),
    ]
