"""
Default micro-check templates for coaching mode.

These templates are automatically seeded when a new brand is created,
providing an immediate "batteries included" experience where managers
can start running Micro-Checks on day 1.

Templates cover industry-standard operational checks across key categories:
- Food Safety & Hygiene (10 templates)
- Cleanliness (10 templates)
- Safety (10 templates)
- PPE - Personal Protective Equipment (10 templates)
- Equipment & Maintenance (10 templates)
- Uniform Compliance (10 templates)
- Menu Board (10 templates)
- Operational Compliance (10 templates)
- Food Quality & Presentation (10 templates)
- Staff Behavior (10 templates)
"""

DEFAULT_TEMPLATES = [
    # ========================================
    # FOOD SAFETY & HYGIENE (10 templates)
    # ========================================
    {
        'title': 'Hand Sink Stocked',
        'category': 'FOOD_SAFETY',
        'severity': 'MEDIUM',
        'description': 'Verify that hand washing station has soap, paper towels, and hot water available for staff.',
        'success_criteria': '• Soap dispenser full or >25% remaining\n• Paper towels stocked\n• Water runs hot (at least 100°F/38°C)\n• Sink is clean and free of debris',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Food Temperature Check',
        'category': 'FOOD_SAFETY',
        'severity': 'CRITICAL',
        'description': 'Verify that hot foods are held at safe temperatures (above 140°F/60°C) and cold foods below 40°F/4°C.',
        'success_criteria': '• Hot holding units at 140°F+ (60°C+)\n• Cold holding units at 40°F- (4°C-)\n• Thermometer readings logged\n• No food in temperature danger zone (40-140°F)',
        'default_photo_required': True,
        'default_video_required': False,
        'expected_completion_seconds': 45,
        'rotation_priority': 90,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Food Storage Proper',
        'category': 'FOOD_SAFETY',
        'severity': 'HIGH',
        'description': 'Check that food is stored properly with raw items below cooked, all items labeled and dated.',
        'success_criteria': '• Raw meat stored below ready-to-eat foods\n• All items labeled with date\n• No expired products visible\n• Shelves clean and organized\n• Items 6 inches off floor',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Sanitizer Buckets Fresh',
        'category': 'FOOD_SAFETY',
        'severity': 'MEDIUM',
        'description': 'Verify sanitizer solution is at proper concentration and changed regularly.',
        'success_criteria': '• Test strips show 200-400 ppm quaternary (or 50-100 ppm chlorine)\n• Solution is clear, not cloudy\n• Buckets labeled and dated\n• Wiping cloths stored in solution',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Prep Surfaces Sanitized',
        'category': 'FOOD_SAFETY',
        'severity': 'HIGH',
        'description': 'Verify all food contact surfaces are clean and sanitized before use.',
        'success_criteria': '• Cutting boards clean with no staining\n• Work tables wiped down and sanitized\n• No food debris in cracks or seams\n• Equipment clean before food prep\n• Sanitizer applied after cleaning',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Refrigeration Temperatures',
        'category': 'FOOD_SAFETY',
        'severity': 'CRITICAL',
        'description': 'Monitor refrigerator and freezer temperatures to ensure food safety.',
        'success_criteria': '• Walk-in cooler at 40°F (4°C) or below\n• Freezer at 0°F (-18°C) or below\n• Reach-in units at proper temps\n• Thermometers visible and accurate\n• Temperatures logged in daily log',
        'default_photo_required': True,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 90,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Dishwasher Sanitizing Correctly',
        'category': 'FOOD_SAFETY',
        'severity': 'HIGH',
        'description': 'Check that dish machine is reaching proper temperatures and sanitizing effectively.',
        'success_criteria': '• Wash temperature 150-165°F (66-74°C)\n• Final rinse temperature 180°F+ (82°C+)\n• Chemicals dispensing properly\n• Test strips confirm sanitization\n• No buildup in spray arms or tanks',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Staff Wearing Gloves Properly',
        'category': 'FOOD_SAFETY',
        'severity': 'HIGH',
        'description': 'Verify staff handling food are wearing clean, intact gloves and changing them appropriately.',
        'success_criteria': '• Staff wear gloves when handling ready-to-eat foods\n• Gloves changed between tasks\n• No torn or dirty gloves in use\n• Gloves changed after touching face/phone/trash\n• Hands washed before putting on gloves',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Hair Restraints Worn',
        'category': 'FOOD_SAFETY',
        'severity': 'MEDIUM',
        'description': 'Check that all food handlers are wearing proper hair restraints (hats, visors, hairnets).',
        'success_criteria': '• All staff in food prep wear hair restraints\n• Hair fully covered (no loose hair visible)\n• Hats/visors clean and in good condition\n• Beards covered if required\n• Restraints worn properly (not just carried)',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Date Labels Current',
        'category': 'FOOD_SAFETY',
        'severity': 'HIGH',
        'description': 'Verify all prepped food and opened containers are properly labeled with dates.',
        'success_criteria': '• All prepped items have date labels\n• Use-by dates clearly visible\n• Labels include prep date and discard date\n• No expired items in coolers\n• FIFO (first in, first out) being followed',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },

    # ========================================
    # CLEANLINESS (10 templates)
    # ========================================
    {
        'title': 'Floors Clean and Dry',
        'category': 'CLEANLINESS',
        'severity': 'MEDIUM',
        'description': 'Check that floors in food prep and service areas are clean, dry, and free of hazards.',
        'success_criteria': '• No visible spills or debris\n• Floors dry (no slip hazards)\n• Corners and edges cleaned\n• Floor drains clear and odor-free\n• Wet floor signs used if mopping',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Trash Containers Managed',
        'category': 'CLEANLINESS',
        'severity': 'LOW',
        'description': 'Check that trash and recycling containers are not overflowing and area is clean.',
        'success_criteria': '• Trash cans <75% full\n• Lids in place and functional\n• No trash on floor around containers\n• Recycling separated properly\n• Outside dumpster area clean',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 40,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Dining Room Clean',
        'category': 'CLEANLINESS',
        'severity': 'MEDIUM',
        'description': 'Check that dining area tables, chairs, and floors are clean and presentable.',
        'success_criteria': '• Tables wiped down and sanitized\n• Chairs free of crumbs and stains\n• Floors swept and mopped\n• Condiment containers clean and filled\n• Windows and glass clean',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Restrooms Sanitized',
        'category': 'CLEANLINESS',
        'severity': 'HIGH',
        'description': 'Verify restrooms are clean, stocked, and sanitary for customer and staff use.',
        'success_criteria': '• Toilets and urinals clean\n• Sinks cleaned and free of buildup\n• Mirrors spotless\n• Floors mopped and dry\n• Supplies stocked (TP, soap, paper towels)\n• No foul odors',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 45,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Kitchen Walls and Ceiling Clean',
        'category': 'CLEANLINESS',
        'severity': 'MEDIUM',
        'description': 'Check that walls, ceilings, and overhead areas are free from grease and dust buildup.',
        'success_criteria': '• No grease accumulation on walls\n• Ceiling tiles clean and intact\n• Exhaust hoods free of dripping grease\n• Light fixtures clean\n• Vents and air returns dust-free',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Dry Storage Area Organized',
        'category': 'CLEANLINESS',
        'severity': 'MEDIUM',
        'description': 'Check that dry storage is clean, organized, and free of pests.',
        'success_criteria': '• Shelves wiped down and organized\n• No signs of pests or droppings\n• Floor swept and clear\n• No damaged or leaking packages\n• Items rotated and organized by type',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Ice Machine Clean',
        'category': 'CLEANLINESS',
        'severity': 'MEDIUM',
        'description': 'Verify ice machine interior and surrounding area are clean and sanitary.',
        'success_criteria': '• Interior walls free of slime/mold\n• Ice scoop stored properly (not in ice)\n• Bin door clean and closing properly\n• No debris in ice\n• Floor area around machine clean',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Beverage Station Clean',
        'category': 'CLEANLINESS',
        'severity': 'MEDIUM',
        'description': 'Check that beverage dispensers, coffee machines, and surrounding areas are clean.',
        'success_criteria': '• Soda nozzles cleaned\n• Drip trays emptied and wiped\n• Coffee pots clean, no burnt residue\n• Counter surfaces wiped down\n• No sticky spills',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Exterior Entrance Clean',
        'category': 'CLEANLINESS',
        'severity': 'MEDIUM',
        'description': 'Verify that entry doors, windows, and immediate exterior area are clean and welcoming.',
        'success_criteria': '• Entry doors clean (no fingerprints/smudges)\n• Windows streak-free\n• Entry mat clean or shaken out\n• No litter within 10 feet of entrance\n• Exterior lights clean and functional',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Prep Equipment Surfaces Clean',
        'category': 'CLEANLINESS',
        'severity': 'MEDIUM',
        'description': 'Check that exterior surfaces of cooking and prep equipment are clean and grease-free.',
        'success_criteria': '• Oven/grill exteriors wiped down\n• Fryer sides free of grease buildup\n• Slicer and mixer exteriors clean\n• Reach-in cooler handles clean\n• No food splatters on equipment sides',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },

    # ========================================
    # SAFETY (10 templates)
    # ========================================
    {
        'title': 'Fire Extinguisher Accessible',
        'category': 'SAFETY',
        'severity': 'HIGH',
        'description': 'Ensure fire extinguishers are visible, accessible, and properly maintained.',
        'success_criteria': '• Extinguisher visible and accessible (not blocked)\n• Pin and seal intact\n• Pressure gauge in green zone\n• Inspection tag current (within 1 year)\n• Mounted securely on wall',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 80,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Exit Paths Clear',
        'category': 'SAFETY',
        'severity': 'HIGH',
        'description': 'Verify all emergency exits and pathways are clear and unobstructed.',
        'success_criteria': '• Exit doors unblocked and operational\n• Exit signs illuminated\n• Aisles and hallways clear\n• No storage blocking exits\n• Doors open freely without resistance',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 85,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Wet Floor Signs Used',
        'category': 'SAFETY',
        'severity': 'MEDIUM',
        'description': 'Check that wet floor signs are deployed when cleaning or when spills occur.',
        'success_criteria': '• Signs available and in good condition\n• Signs placed when mopping or cleaning\n• Signs visible from all approaches\n• Floors dried promptly after cleaning',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Chemical Storage Safe',
        'category': 'SAFETY',
        'severity': 'HIGH',
        'description': 'Verify cleaning chemicals are stored properly away from food and properly labeled.',
        'success_criteria': '• Chemicals stored separately from food\n• All containers properly labeled\n• Lids closed when not in use\n• Storage area ventilated\n• Safety Data Sheets (SDS) accessible',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'First Aid Kit Stocked',
        'category': 'SAFETY',
        'severity': 'MEDIUM',
        'description': 'Check that first aid kit is accessible, stocked, and supplies are not expired.',
        'success_criteria': '• Kit easily accessible to staff\n• Bandages, gauze, and tape present\n• Burn gel and cold packs available\n• No expired items\n• Kit contents listed on outside',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Emergency Lighting Functional',
        'category': 'SAFETY',
        'severity': 'MEDIUM',
        'description': 'Verify emergency exit lights and emergency lighting are operational.',
        'success_criteria': '• Exit signs illuminated\n• Emergency lights tested monthly\n• Backup battery lights functional\n• No burned out bulbs in exit signs\n• Test button confirms operation',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Ladder Safety Check',
        'category': 'SAFETY',
        'severity': 'MEDIUM',
        'description': 'Check that ladders are in good condition and stored safely.',
        'success_criteria': '• Ladder steps/rungs intact and secure\n• No cracks or damage to frame\n• Rubber feet present and not worn\n• Safety locks functional (step ladders)\n• Stored securely when not in use',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 45,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Electrical Cords Safe',
        'category': 'SAFETY',
        'severity': 'MEDIUM',
        'description': 'Verify electrical cords and outlets are in safe condition with no hazards.',
        'success_criteria': '• No frayed or damaged cords\n• Cords not running through water/wet areas\n• Outlets not overloaded\n• No extension cords daisy-chained\n• GFCI outlets functional in wet areas',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Knife Storage Safe',
        'category': 'SAFETY',
        'severity': 'MEDIUM',
        'description': 'Check that knives are stored safely in blocks, magnetic strips, or sheaths.',
        'success_criteria': '• Knives not left loose in drawers\n• Knife block or magnetic strip used\n• Sharp knives stored separately from utensils\n• No knives left in sinks or submerged in water\n• Staff trained on proper handling',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Anti-Slip Mats in Place',
        'category': 'SAFETY',
        'severity': 'MEDIUM',
        'description': 'Verify anti-slip mats are in place in wet areas and in good condition.',
        'success_criteria': '• Mats present at sinks and dish area\n• Mats laying flat (no curled edges)\n• Mats cleaned regularly\n• No excessive wear or holes\n• Adequate coverage in high-traffic wet areas',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },

    # ========================================
    # PPE - PERSONAL PROTECTIVE EQUIPMENT (10 templates)
    # ========================================
    {
        'title': 'Cut-Resistant Gloves Available',
        'category': 'PPE',
        'severity': 'MEDIUM',
        'description': 'Verify cut-resistant gloves are available for staff using slicers, graters, and knives.',
        'success_criteria': '• Cut gloves available in multiple sizes\n• Gloves clean and in good condition\n• Staff trained on when to use\n• No holes or excessive wear\n• Stored in accessible location',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Non-Slip Shoes Worn',
        'category': 'PPE',
        'severity': 'HIGH',
        'description': 'Check that kitchen and service staff are wearing proper non-slip footwear.',
        'success_criteria': '• All staff wear closed-toe shoes\n• Shoes have slip-resistant soles\n• No canvas, mesh, or open-toe shoes\n• Shoes in good repair (no holes)\n• Soles not excessively worn',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Oven Mitts/Heat Gloves Available',
        'category': 'PPE',
        'severity': 'MEDIUM',
        'description': 'Verify adequate oven mitts or heat-resistant gloves are available and in good condition.',
        'success_criteria': '• At least 2 pairs of oven mitts available\n• Mitts dry and clean\n• No holes or thin spots\n• Long enough to protect forearms\n• Stored near hot equipment',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Aprons Clean and Used',
        'category': 'PPE',
        'severity': 'LOW',
        'description': 'Check that staff wear clean aprons when handling food or washing dishes.',
        'success_criteria': '• Staff in food prep wearing aprons\n• Aprons clean and not excessively stained\n• Dishwasher staff wearing waterproof aprons\n• Aprons changed when soiled\n• Adequate supply of clean aprons',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 40,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Safety Goggles Available',
        'category': 'PPE',
        'severity': 'MEDIUM',
        'description': 'Verify safety goggles are available for tasks involving chemicals or splashing.',
        'success_criteria': '• Goggles available near chemical storage\n• Goggles clean with clear lenses\n• Straps intact and functional\n• Staff trained on when to use\n• At least one pair per shift',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Back Support Belts Available',
        'category': 'PPE',
        'severity': 'LOW',
        'description': 'Check that back support belts are available for staff doing heavy lifting.',
        'success_criteria': '• Support belts available in stock area\n• Multiple sizes available\n• Belts in good condition\n• Staff trained on proper use\n• Posted signage about availability',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 35,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Disposable Glove Supply',
        'category': 'PPE',
        'severity': 'MEDIUM',
        'description': 'Verify adequate supply of disposable food service gloves in multiple sizes.',
        'success_criteria': '• Small, medium, and large gloves stocked\n• At least 2 boxes per size available\n• Gloves stored away from contaminants\n• Glove boxes easily accessible\n• No damaged or opened packages',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Face Shields Available',
        'category': 'PPE',
        'severity': 'LOW',
        'description': 'Check that face shields are available for tasks requiring face protection.',
        'success_criteria': '• Face shields available if needed\n• Shields clean with no cracks\n• Headband/mounting functional\n• Staff know when to use\n• Stored in accessible location',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 30,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Hearing Protection Available',
        'category': 'PPE',
        'severity': 'LOW',
        'description': 'Verify hearing protection is available for staff working in loud environments.',
        'success_criteria': '• Earplugs or earmuffs available\n• Protection appropriate for noise level\n• Individual sealed earplugs for each user\n• Staff aware of availability\n• Posted in areas with loud equipment',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 35,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Bandage/Finger Cot Supply',
        'category': 'PPE',
        'severity': 'MEDIUM',
        'description': 'Check that bandages and finger cots are stocked for covering cuts and wounds.',
        'success_criteria': '• Blue bandages available (metal-detectable)\n• Finger cots in stock\n• Supplies in first aid kit\n• Staff know where to find them\n• Gloves required over bandages for food prep',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },

    # ========================================
    # EQUIPMENT & MAINTENANCE (10 templates)
    # ========================================
    {
        'title': 'Equipment Maintenance Log Current',
        'category': 'EQUIPMENT',
        'severity': 'MEDIUM',
        'description': 'Verify equipment maintenance logs are up to date and completed.',
        'success_criteria': '• Daily temperature logs filled out\n• Maintenance schedule posted\n• Recent service dates recorded\n• Equipment manuals accessible\n• Contact info for repair services available',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Thermometer Calibration',
        'category': 'EQUIPMENT',
        'severity': 'MEDIUM',
        'description': 'Check that food thermometers are calibrated and functioning accurately.',
        'success_criteria': '• Thermometers read 32°F (0°C) in ice water\n• Digital thermometers have working batteries\n• At least 2 calibrated thermometers available\n• Calibration log maintained\n• Damaged thermometers removed from service',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Hood Filter Cleaning Status',
        'category': 'EQUIPMENT',
        'severity': 'MEDIUM',
        'description': 'Verify exhaust hood filters are clean or recently serviced.',
        'success_criteria': '• Filters not excessively greasy\n• Cleaning schedule posted and followed\n• Filters securely mounted\n• Hood system functioning (good suction)\n• Professional cleaning within last 90 days',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Refrigerator Door Seals Intact',
        'category': 'EQUIPMENT',
        'severity': 'MEDIUM',
        'description': 'Check that cooler and freezer door gaskets seal properly without gaps.',
        'success_criteria': '• Gaskets clean and flexible\n• No cracks or tears in seals\n• Doors close easily and seal tight\n• Paper test: paper held by closed door\n• No frost buildup around door edges',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Slicer Blade Sharp and Clean',
        'category': 'EQUIPMENT',
        'severity': 'MEDIUM',
        'description': 'Verify meat/cheese slicer is clean, blade is sharp, and safety features work.',
        'success_criteria': '• Blade clean with no food buildup\n• Blade guard in place and functional\n• Cuts cleanly without tearing\n• No rust on blade or parts\n• Cleaning log shows recent deep clean',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Fryer Oil Quality',
        'category': 'EQUIPMENT',
        'severity': 'MEDIUM',
        'description': 'Check fryer oil color, smell, and quality using test strips.',
        'success_criteria': '• Oil not excessively dark\n• No burnt or rancid smell\n• Test strips show acceptable levels\n• Filter/boil-out schedule followed\n• Oil change dates logged',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Grease Trap Maintenance',
        'category': 'EQUIPMENT',
        'severity': 'MEDIUM',
        'description': 'Verify grease trap is pumped regularly and not backing up.',
        'success_criteria': '• Service sticker shows recent pump-out\n• No foul odors from drains\n• Drains flowing freely\n• Service within last 90 days\n• Service company contact posted',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Oven Temperature Accuracy',
        'category': 'EQUIPMENT',
        'severity': 'MEDIUM',
        'description': 'Check that ovens are heating to correct temperatures using oven thermometer.',
        'success_criteria': '• Oven thermometer shows accurate temps\n• Ovens reach set temperature\n• No hot/cold spots noted by staff\n• Thermometer calibrated within last 6 months\n• Gas burners ignite properly',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Water Filter Replacement',
        'category': 'EQUIPMENT',
        'severity': 'LOW',
        'description': 'Verify water filters for ice machines and beverage systems are replaced on schedule.',
        'success_criteria': '• Filter change date sticker visible\n• Filters changed per manufacturer schedule\n• No excessive mineral buildup\n• Water pressure adequate\n• Replacement filters in stock',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 45,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Knife Sharpness',
        'category': 'EQUIPMENT',
        'severity': 'MEDIUM',
        'description': 'Check that kitchen knives are sharp and in safe working condition.',
        'success_criteria': '• Knives cut cleanly without sawing\n• No excessive force needed\n• Paper test: easily slices paper\n• Sharpening schedule followed\n• Dull knives removed for sharpening',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },

    # ========================================
    # UNIFORM COMPLIANCE (10 templates)
    # ========================================
    {
        'title': 'Name Tags Worn',
        'category': 'UNIFORM',
        'severity': 'LOW',
        'description': 'Check that all customer-facing staff are wearing visible name tags.',
        'success_criteria': '• Name tags visible and legible\n• Correct name displayed\n• Tag pinned/attached securely\n• Tag clean and professional\n• All FOH staff wearing tags',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 40,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Uniform Shirt Clean and Pressed',
        'category': 'UNIFORM',
        'severity': 'MEDIUM',
        'description': 'Verify staff uniforms are clean, pressed, and in good repair.',
        'success_criteria': '• Shirts clean with no stains\n• Minimal wrinkles (pressed or neat)\n• Correct uniform style worn\n• No holes or tears\n• Logo/branding visible if required',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Proper Pants/Bottoms',
        'category': 'UNIFORM',
        'severity': 'MEDIUM',
        'description': 'Check that staff wear approved pants, skirts, or uniform bottoms.',
        'success_criteria': '• Correct color/style per policy\n• Clean and professional appearance\n• Proper length (not dragging)\n• No rips or excessive wear\n• Belt worn if required',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Jewelry Policy Followed',
        'category': 'UNIFORM',
        'severity': 'MEDIUM',
        'description': 'Verify staff comply with jewelry restrictions (especially in food prep areas).',
        'success_criteria': '• No jewelry beyond plain band ring\n• No bracelets or watches in food prep\n• No dangling earrings\n• Necklaces tucked in or not worn\n• Medical alert jewelry acceptable',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Hair Neat and Professional',
        'category': 'UNIFORM',
        'severity': 'MEDIUM',
        'description': 'Check that staff hair is neat, clean, and styled professionally.',
        'success_criteria': '• Hair clean and styled\n• Long hair tied back in food areas\n• Hair color appropriate per policy\n• No extreme styles (if policy exists)\n• Facial hair groomed',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 45,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Appropriate Footwear',
        'category': 'UNIFORM',
        'severity': 'HIGH',
        'description': 'Verify staff wear appropriate footwear per uniform policy and safety requirements.',
        'success_criteria': '• Closed-toe shoes (no sandals)\n• Clean and professional appearance\n• Non-slip soles in kitchen\n• Shoes in good repair\n• Appropriate color per policy',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Visible Tattoos Policy',
        'category': 'UNIFORM',
        'severity': 'LOW',
        'description': 'Check that staff follow company policy regarding visible tattoos (if policy exists).',
        'success_criteria': '• Tattoos covered if required by policy\n• Long sleeves or bandages used if needed\n• Policy followed consistently\n• No offensive imagery visible\n• Staff aware of policy',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 30,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Nails Clean and Trimmed',
        'category': 'UNIFORM',
        'severity': 'MEDIUM',
        'description': 'Verify food handlers have short, clean nails per health code requirements.',
        'success_criteria': '• Nails trimmed short (especially food handlers)\n• Nails clean (no visible dirt)\n• No artificial nails in food prep\n• No chipped nail polish in food areas\n• Hand hygiene maintained',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Hat or Visor Worn',
        'category': 'UNIFORM',
        'severity': 'LOW',
        'description': 'Check that staff wear required hats or visors per uniform policy.',
        'success_criteria': '• Hat/visor worn if required\n• Headwear clean and in good condition\n• Correct style/color per policy\n• Logo visible if branded\n• Worn properly (not backwards unless allowed)',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 35,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Overall Appearance Professional',
        'category': 'UNIFORM',
        'severity': 'MEDIUM',
        'description': 'Check that staff present a clean, professional overall appearance.',
        'success_criteria': '• Good personal hygiene\n• Fresh appearance (not disheveled)\n• Minimal cologne/perfume\n• No excessive makeup\n• Professional demeanor',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },

    # ========================================
    # MENU BOARD (10 templates)
    # ========================================
    {
        'title': 'Pricing Accurate',
        'category': 'MENU_BOARD',
        'severity': 'HIGH',
        'description': 'Verify menu board prices match POS system and current pricing.',
        'success_criteria': '• All prices match POS\n• Recent price changes updated\n• No faded or illegible prices\n• Combo/meal prices correct\n• Promotional pricing accurate',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Daily Specials Updated',
        'category': 'MENU_BOARD',
        'severity': 'MEDIUM',
        'description': 'Check that daily specials board is updated and accurate for today.',
        'success_criteria': '• Specials board shows today\'s date\n• Items listed are available\n• Prices clearly marked\n• Neatly written or printed\n• Old specials removed',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Menu Board Clean and Lit',
        'category': 'MENU_BOARD',
        'severity': 'MEDIUM',
        'description': 'Verify menu boards are clean, well-lit, and easily readable.',
        'success_criteria': '• Backlit boards illuminated fully\n• No burned out bulbs/LEDs\n• Surface clean (no smudges/dust)\n• Letters/graphics not faded\n• Clearly visible from ordering area',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Allergen Information Available',
        'category': 'MENU_BOARD',
        'severity': 'HIGH',
        'description': 'Check that allergen information is posted or readily available to customers.',
        'success_criteria': '• Allergen guide posted or available\n• Staff trained on allergen inquiries\n• Common allergens marked on menu\n• Information current and accurate\n• Clear signage directing to allergen info',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Seasonal Items Updated',
        'category': 'MENU_BOARD',
        'severity': 'MEDIUM',
        'description': 'Verify seasonal or limited-time items are current and available.',
        'success_criteria': '• LTO (limited time offer) items displayed\n• Seasonal items match current season\n• Out-of-season items removed\n• Availability confirmed with kitchen\n• End dates visible if applicable',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Combo Meals Clearly Displayed',
        'category': 'MENU_BOARD',
        'severity': 'MEDIUM',
        'description': 'Check that combo meals are clearly listed with included items and pricing.',
        'success_criteria': '• Combo options easy to identify\n• Included items listed clearly\n• Value/savings communicated\n• Upcharge options marked\n• Photos match actual combos (if using images)',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Nutritional Claims Compliant',
        'category': 'MENU_BOARD',
        'severity': 'HIGH',
        'description': 'Verify any nutritional or health claims on menu comply with regulations.',
        'success_criteria': '• "Healthy", "low-fat" claims substantiated\n• Calorie counts accurate (if listed)\n• No misleading health statements\n• Compliance with local regulations\n• Documentation available if required',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Photos Match Products',
        'category': 'MENU_BOARD',
        'severity': 'MEDIUM',
        'description': 'Check that menu photos accurately represent actual menu items served.',
        'success_criteria': '• Photos match portion sizes\n• Presentation similar to photos\n• No misleading images\n• Quality standards match photos\n• Photos updated when recipes change',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Out-of-Stock Items Covered',
        'category': 'MENU_BOARD',
        'severity': 'HIGH',
        'description': 'Verify items that are out of stock are clearly marked or covered on menu.',
        'success_criteria': '• 86\'d items covered or marked\n• Staff aware of items to alert\n• Signage clear and visible\n• Alternative suggestions trained\n• Board updated when items return',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Menu Organization Logical',
        'category': 'MENU_BOARD',
        'severity': 'LOW',
        'description': 'Check that menu is organized in a logical, easy-to-navigate way.',
        'success_criteria': '• Items grouped by category\n• Logical flow (appetizers, mains, desserts)\n• High-margin items prominently placed\n• Easy to scan quickly\n• Not cluttered or overwhelming',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 40,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },

    # ========================================
    # OPERATIONAL COMPLIANCE (10 templates)
    # ========================================
    {
        'title': 'Opening Checklist Complete',
        'category': 'OPERATIONAL',
        'severity': 'MEDIUM',
        'description': 'Verify opening shift checklist is completed and signed off.',
        'success_criteria': '• Checklist filled out completely\n• All items checked off\n• Manager signature present\n• Time documented\n• Any issues noted in log',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Closing Checklist Complete',
        'category': 'OPERATIONAL',
        'severity': 'MEDIUM',
        'description': 'Check that closing duties are documented and completed properly.',
        'success_criteria': '• All closing tasks checked off\n• Cash drawer balanced and logged\n• Equipment turned off/cleaned\n• Closing manager signature\n• Secure lockup documented',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Cash Handling Procedures',
        'category': 'OPERATIONAL',
        'severity': 'HIGH',
        'description': 'Verify cash handling procedures are being followed correctly.',
        'success_criteria': '• Cash drawer starts with correct bank\n• Bills organized by denomination\n• Large bills dropped to safe\n• No excessive cash in drawer\n• Two-person counts when required',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Inventory Par Levels',
        'category': 'OPERATIONAL',
        'severity': 'MEDIUM',
        'description': 'Check that key inventory items meet minimum par levels.',
        'success_criteria': '• Core ingredients at par level\n• No critical items out of stock\n• Reorder points documented\n• Manager aware of low stock\n• Orders placed for needed items',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Daily Sales Report Complete',
        'category': 'OPERATIONAL',
        'severity': 'MEDIUM',
        'description': 'Verify daily sales report is completed and reviewed by management.',
        'success_criteria': '• Sales entered in system\n• Variances investigated\n• Report reviewed by manager\n• Comparisons to previous day/week\n• Any issues documented',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Labor Schedule Posted',
        'category': 'OPERATIONAL',
        'severity': 'MEDIUM',
        'description': 'Check that current week staff schedule is posted and visible.',
        'success_criteria': '• Schedule posted in break area\n• Current week clearly marked\n• All shifts filled and covered\n• Call-out procedures posted\n• Changes communicated to staff',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Required Posters Displayed',
        'category': 'OPERATIONAL',
        'severity': 'HIGH',
        'description': 'Verify all legally required labor law and safety posters are displayed.',
        'success_criteria': '• OSHA posters current and visible\n• Minimum wage poster displayed\n• Workers comp information posted\n• Equal opportunity poster visible\n• Posters in break room or office',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Health Permit Current',
        'category': 'OPERATIONAL',
        'severity': 'CRITICAL',
        'description': 'Check that health department permit is current and properly displayed.',
        'success_criteria': '• Permit displayed near entrance\n• Current year/date valid\n• Score visible if required\n• No violations outstanding\n• Renewal date tracked',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 85,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Incident Report Log',
        'category': 'OPERATIONAL',
        'severity': 'MEDIUM',
        'description': 'Verify incident reports are documented and filed for any accidents or issues.',
        'success_criteria': '• Incident log book accessible\n• Recent incidents documented\n• Follow-up actions noted\n• Manager review signatures\n• Reports filed with corporate if required',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Manager on Duty Identified',
        'category': 'OPERATIONAL',
        'severity': 'MEDIUM',
        'description': 'Check that manager on duty is clearly identified and present.',
        'success_criteria': '• MOD identified on schedule board\n• Manager present during shift\n• Staff know who to contact\n• Manager badge/identifier worn\n• Backup manager plan in place',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 20,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },

    # ========================================
    # FOOD QUALITY & PRESENTATION (10 templates)
    # ========================================
    {
        'title': 'Portion Control Accuracy',
        'category': 'FOOD_QUALITY',
        'severity': 'MEDIUM',
        'description': 'Check that food portions are consistent and meet brand standards.',
        'success_criteria': '• Portions measured using scoops/scales\n• Protein portions accurate\n• Side portions consistent\n• No under or over-portioning\n• Portioning tools available at stations',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Plating Standards Met',
        'category': 'FOOD_QUALITY',
        'severity': 'MEDIUM',
        'description': 'Verify dishes are plated attractively per brand presentation standards.',
        'success_criteria': '• Plate composition follows photos/guides\n• Garnishes applied correctly\n• Plate rims clean (no smudges)\n• Food centered and arranged neatly\n• Consistent presentation across orders',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Recipe Adherence',
        'category': 'FOOD_QUALITY',
        'severity': 'HIGH',
        'description': 'Check that staff follow standardized recipes and prep procedures.',
        'success_criteria': '• Recipe cards posted at stations\n• Ingredients measured correctly\n• Prep methods followed\n• No unauthorized substitutions\n• Recipes updated when changed',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Garnish Freshness',
        'category': 'FOOD_QUALITY',
        'severity': 'MEDIUM',
        'description': 'Verify garnishes (lettuce, herbs, lemon) are fresh and not wilted.',
        'success_criteria': '• Lettuce crisp, not brown\n• Herbs fresh and green\n• Fruit garnishes not dried out\n• Garnish bins iced/refrigerated\n• Old garnishes discarded',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Food Temperature at Service',
        'category': 'FOOD_QUALITY',
        'severity': 'HIGH',
        'description': 'Check that hot food is served hot and cold food is served cold.',
        'success_criteria': '• Hot dishes >140°F when served\n• Cold dishes <40°F when served\n• Plates pre-warmed for hot dishes (if standard)\n• No lukewarm food leaving kitchen\n• Hold times followed',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 40,
        'rotation_priority': 75,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Bread/Buns Fresh',
        'category': 'FOOD_QUALITY',
        'severity': 'MEDIUM',
        'description': 'Verify bread products are fresh, not stale, and properly toasted if required.',
        'success_criteria': '• Bread soft, not dried out\n• Buns toasted to correct level\n• No stale or moldy bread in use\n• Bread storage proper (sealed bags)\n• FIFO rotation followed',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Cook Temperatures Correct',
        'category': 'FOOD_QUALITY',
        'severity': 'CRITICAL',
        'description': 'Check that proteins are cooked to proper internal temperatures per order.',
        'success_criteria': '• Thermometer used for temp checks\n• Steaks at requested doneness\n• Chicken at 165°F minimum\n• Ground beef at 155°F minimum\n• Pork at 145°F minimum',
        'default_photo_required': True,
        'default_video_required': False,
        'expected_completion_seconds': 45,
        'rotation_priority': 85,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Sauce Consistency',
        'category': 'FOOD_QUALITY',
        'severity': 'MEDIUM',
        'description': 'Verify sauces, gravies, and dressings are correct consistency and flavor.',
        'success_criteria': '• Sauces not too thick or thin\n• Seasoning levels correct\n• No separation or curdling\n• Temperatures appropriate\n• Fresh batches prepared regularly',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Food Waste Minimized',
        'category': 'FOOD_QUALITY',
        'severity': 'MEDIUM',
        'description': 'Check that food waste is tracked and kitchen works to minimize waste.',
        'success_criteria': '• Waste log maintained\n• Trimming/prep waste minimized\n• Overproduction avoided\n• Proper storage prevents spoilage\n• Staff trained on waste reduction',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Expeditor Quality Check',
        'category': 'FOOD_QUALITY',
        'severity': 'HIGH',
        'description': 'Verify expo/pass station is checking each plate before service.',
        'success_criteria': '• Every plate inspected before leaving\n• Quality standards enforced\n• Incorrect plates sent back\n• Garnish and presentation checked\n• Manager involvement in expo',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 35,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },

    # ========================================
    # STAFF BEHAVIOR (10 templates)
    # ========================================
    {
        'title': 'Customer Greeting Prompt',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'MEDIUM',
        'description': 'Check that staff promptly greet customers upon arrival.',
        'success_criteria': '• Greeting within 30 seconds of arrival\n• Eye contact and smile\n• Friendly, welcoming tone\n• Name offered (if policy)\n• Guest acknowledged even if busy',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Teamwork Observed',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'MEDIUM',
        'description': 'Verify staff are working together cooperatively and helping each other.',
        'success_criteria': '• Staff assisting each other\n• Good communication between team\n• No standing idle while others swamped\n• Positive attitude\n• Respectful interactions',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 55,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Phone Etiquette Professional',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'MEDIUM',
        'description': 'Check that phone calls are answered professionally with proper greeting.',
        'success_criteria': '• Phone answered within 3 rings\n• Proper greeting used\n• Clear, friendly voice\n• Accurate information provided\n• Call ended politely',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'No Cell Phone Use',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'MEDIUM',
        'description': 'Verify staff are not using personal cell phones during shifts.',
        'success_criteria': '• No phones visible on floor\n• No texting during shift\n• Phones stored in locker/back\n• Emergencies handled in back area\n• Policy enforced consistently',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Positive Body Language',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'MEDIUM',
        'description': 'Check that staff exhibit positive body language and good posture.',
        'success_criteria': '• Standing up straight (not slouching)\n• Attentive posture\n• No arms crossed\n• Facing customers\n• Engaged and alert',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 50,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Complaint Handling Appropriate',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'HIGH',
        'description': 'Verify staff handle customer complaints professionally and escalate properly.',
        'success_criteria': '• Staff listen without interrupting\n• Empathy expressed\n• Solution offered or manager called\n• Calm, professional demeanor\n• Issue documented',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 70,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Punctuality and Attendance',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'MEDIUM',
        'description': 'Check that staff arrive on time and follow attendance policies.',
        'success_criteria': '• Staff arrive 5-10 min before shift\n• Time clock used properly\n• Call-outs follow policy\n• No pattern of tardiness\n• Shift coverage arranged when needed',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Following Instructions',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'MEDIUM',
        'description': 'Verify staff follow manager instructions and complete assigned tasks.',
        'success_criteria': '• Tasks completed as assigned\n• Clarifying questions asked if needed\n• Instructions followed correctly\n• No pushback or resistance\n• Proactive task completion',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Professional Language Used',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'MEDIUM',
        'description': 'Check that staff use appropriate, professional language (no profanity).',
        'success_criteria': '• No profanity or crude language\n• Professional terms used\n• Respectful tone with all\n• Appropriate volume (not shouting)\n• Slang minimized',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 25,
        'rotation_priority': 60,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
    {
        'title': 'Hustle and Urgency',
        'category': 'STAFF_BEHAVIOR',
        'severity': 'MEDIUM',
        'description': 'Verify staff move with appropriate sense of urgency during busy times.',
        'success_criteria': '• Fast-paced movement during rush\n• No excessive socializing\n• Quick transitions between tasks\n• Awareness of ticket times\n• Energetic, not lethargic',
        'default_photo_required': False,
        'default_video_required': False,
        'expected_completion_seconds': 30,
        'rotation_priority': 65,
        'ai_validation_enabled': False,
        'ai_validation_prompt': '',
    },
]


def get_default_templates():
    """
    Returns the list of default coaching templates.

    Returns:
        list: List of template dictionaries ready for MicroCheckTemplate.objects.create()
    """
    return DEFAULT_TEMPLATES.copy()


def get_template_count():
    """Returns the number of default templates"""
    return len(DEFAULT_TEMPLATES)


def get_templates_by_category():
    """Returns templates grouped by category"""
    from collections import defaultdict
    grouped = defaultdict(list)
    for template in DEFAULT_TEMPLATES:
        grouped[template['category']].append(template)
    return dict(grouped)
