# Generated by Django 4.2.23 on 2025-10-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brand_has_enterprise_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='consolidated_into',
            field=models.ForeignKey(blank=True, help_text='If this trial brand was consolidated into an enterprise brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidated_brands', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='focus_areas',
            field=models.JSONField(blank=True, default=list, help_text='Array of operational focus areas (food_safety, cleanliness, etc)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='industry',
            field=models.CharField(blank=True, choices=[('RESTAURANT', 'Restaurant'), ('RETAIL', 'Retail'), ('HOSPITALITY', 'Hospitality'), ('OTHER', 'Other')], help_text='Primary industry vertical', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When brand profile was completed', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='store_count_range',
            field=models.CharField(blank=True, choices=[('1-2', '1-2 locations'), ('3-10', '3-10 locations'), ('10+', '10+ locations'), ('CORPORATE', 'Corporate/Franchise')], help_text='Number of locations', max_length=20, null=True),
        ),
    ]
