# Generated by Django 4.2.24 on 2025-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_add_onboarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='store_count_range',
            field=models.CharField(blank=True, help_text='Number of locations (flexible format for industry-specific ranges)', max_length=50, null=True),
        ),
    ]
