# Generated by Django 4.2.24 on 2025-10-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_update_store_count_range_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
