# Generated by Django 4.2.23 on 2025-10-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_store_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='micro_check_send_time',
            field=models.TimeField(default='08:00:00', help_text="Local time to send daily micro-check emails (in store's timezone)"),
        ),
    ]
