# Generated by Django 4.2.25 on 2025-10-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_user_account_and_more'),
        ('brands', '0007_store_micro_check_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Franchisee account that operates this store', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='store',
            name='brand',
            field=models.ForeignKey(help_text='Parent brand (for reporting and brand-level templates)', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='brands.brand'),
        ),
    ]
