# Generated by Django 4.2.23 on 2025-10-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_store_account_alter_store_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='subtype',
            field=models.CharField(blank=True, choices=[('QSR', 'Quick Service / Fast Food'), ('FAST_CASUAL', 'Fast Casual'), ('CASUAL_DINING', 'Casual Dining'), ('FINE_DINING', 'Fine Dining'), ('CAFE', 'Cafe / Coffee Shop'), ('BAR_PUB', 'Bar / Pub'), ('FOOD_TRUCK', 'Food Truck'), ('CATERING', 'Catering'), ('BAKERY', 'Bakery / Dessert Shop'), ('GROCERY', 'Grocery Store'), ('CONVENIENCE', 'Convenience Store'), ('FASHION', 'Fashion Retail'), ('HOTEL', 'Hotel'), ('OTHER_SUBTYPE', 'Other')], help_text='Industry subtype (e.g., QSR, Fine Dining for restaurants)', max_length=50, null=True),
        ),
    ]
