# Generated by Django 4.2.25 on 2025-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_brand_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='segment',
            field=models.CharField(blank=True, choices=[('low_vol', 'Low Volume'), ('med_vol', 'Medium Volume'), ('high_vol', 'High Volume')], db_index=True, help_text='Store segment for ML model grouping (low/med/high volume)', max_length=20, null=True),
        ),
    ]
